# Curated catalogue: the art of friends — pairs, companions and companies,
# weighted toward the abstract-yet-human, as in the love and parents galleries.
#
# `file` -> exact Wikimedia Commons file title (verified to exist)
# `q`    -> Commons search query; the resolver takes the first result that is
#          public domain or CC0.

WORKS = [
    # ---- I. Two Figures ------------------------------------------------
    dict(slug="ruth-naomi", file="File:'Ruth and Naomi' by Jan Victors, 1653.jpg",
         title="Ruth and Naomi",
         artist="Jan Victors (1619-1676)", date="1653",
         medium="Oil on canvas", place="",
         note="Ruth clings to her mother-in-law and refuses to go back to her own people, and the whole of loyalty is in the grip of one woman on another. A friendship chosen against every obligation.",
         tags=["dutch", "loyalty"]),
    dict(slug="visitation", file="File:Giotto - Scrovegni - -16- - Visitation.jpg",
         title="The Visitation",
         artist="Giotto di Bondone (c. 1267-1337)", date="c. 1306",
         medium="Fresco", place="Scrovegni Chapel, Padua",
         note="Two women greet each other outside a house, and the friendship is entirely in the angle of two bodies leaning in. Giotto makes the embrace architectural.",
         tags=["fresco", "the pair"]),
    dict(slug="achilles-patroclus", file="File:Akhilleus Patroklos Antikensammlung Berlin F2278.jpg",
         title="Achilles Tending the Wound of Patroclus",
         artist="Sosias Painter, Athens", date="c. 500 BC",
         medium="Red-figure kylix", place="Antikensammlung, Berlin",
         note="One warrior bandages the arm of the other and neither of them looks up. The most tender image of friendship in ancient painting, and it is almost entirely a matter of two bowed heads.",
         tags=["red figure", "care"]),
    dict(slug="david-jonathan", q="Rembrandt David and Jonathan 1642 Hermitage",
         title="David and Jonathan",
         artist="Rembrandt van Rijn (1606-1669)", date="1642",
         medium="Oil on canvas", place="Hermitage Museum, Saint Petersburg",
         note="Jonathan collapses into David's arms while Saul's anger burns behind a curtain. Rembrandt paints the farewell of friends as one dark mass with two heads.",
         tags=["baroque", "the pair"]),
    dict(slug="two-men-moon", q="Caspar David Friedrich Two Men Contemplating the Moon",
         title="Two Men Contemplating the Moon",
         artist="Caspar David Friedrich (1774-1840)", date="1819-20",
         medium="Oil on canvas", place="Alte Nationalgalerie, Berlin",
         note="Two men stand with their backs to us looking at the same thing, and the friendship is entirely in the identical posture. Friedrich paints company as a shared direction of attention.",
         tags=["romanticism", "attention"]),

    # ---- II. Making Music Together --------------------------------------
    dict(slug="the-concert-vermeer", q="Vermeer The Concert",
         title="The Concert",
         artist="Johannes Vermeer (1632-1675)", date="c. 1664",
         medium="Oil on canvas", place="Isabella Stewart Gardner Museum, Boston",
         note="Three people make music in a room and the friendship is in the tuning: each of them is listening rather than looking. Vermeer paints company as a shared surface of light.",
         tags=["music", "interior"]),
    dict(slug="the-musicians-caravaggio", q="Caravaggio The Musicians Metropolitan Museum",
         title="The Musicians",
         artist="Caravaggio (1571-1610)", date="c. 1597",
         medium="Oil on canvas", place="The Metropolitan Museum of Art, New York",
         note="Four young men rehearse a song, one of them seen only as a face in the shadow. Caravaggio arranges a group of friends as a single piece of theatre.",
         tags=["baroque", "music"]),
    dict(slug="three-musicians", q="Velazquez The Three Musicians Berlin",
         title="The Three Musicians",
         artist="Diego Velázquez (1599-1660)", date="1618",
         medium="Oil on canvas", place="Gemäldegalerie, Berlin",
         note="Three men sing and play at a plain table, and the comedy is in the way they look at each other rather than at us. Velázquez paints friendship as an exchange of glances.",
         tags=["baroque", "music"]),
    dict(slug="concert-honthorst", file="File:Honthorst - Le Concert, 1624, INV 1364.jpg",
         title="The Concert",
         artist="Gerrit van Honthorst (1592-1656)", date="1624",
         medium="Oil on canvas", place="Musée du Louvre, Paris",
         note="A group of musicians gathers around a candlelit table, one of them singing from a book. Honthorst paints company as a circle of light with four faces in it.",
         tags=["caravaggisti", "music"]),
    dict(slug="music-in-the-tuileries", q="Manet Music in the Tuileries Gardens",
         title="Music in the Tuileries Gardens",
         artist="Édouard Manet (1832-1883)", date="1862",
         medium="Oil on canvas", place="National Gallery, London",
         note="Manet crowds his friends into a garden bandstand until the friendship is a density rather than a set of faces. A group portrait dissolved into a crowd.",
         tags=["impressionism", "the crowd"]),

    # ---- III. A Portrait of Friends --------------------------------------
    dict(slug="hommage-delacroix", q="Fantin-Latour Hommage a Delacroix 1864",
         title="Hommage à Delacroix",
         artist="Henri Fantin-Latour (1836-1904)", date="1864",
         medium="Oil on canvas", place="Musée d'Orsay, Paris",
         note="Ten artists stand and sit around a portrait of a dead painter, and the homage is arranged as a row of pale faces in dark coats. Friendship as a shared debt.",
         tags=["group portrait", "homage"]),
    dict(slug="studio-batignolles", q="Fantin-Latour A Studio at Les Batignolles",
         title="A Studio at Les Batignolles",
         artist="Henri Fantin-Latour (1836-1904)", date="1870",
         medium="Oil on canvas", place="Musée d'Orsay, Paris",
         note="Manet paints at his easel while his friends gather round him, and the group is arranged as a pyramid of attention. Friendship as the act of watching someone work.",
         tags=["group portrait", "the studio"]),
    dict(slug="rue-de-la-condamine", q="Bazille Studio on the Rue de la Condamine",
         title="The Studio on the Rue de la Condamine",
         artist="Frédéric Bazille (1841-1870)", date="1870",
         medium="Oil on canvas", place="Musée d'Orsay, Paris",
         note="Bazille paints his own studio from the inside with his friends scattered up a staircase. A group portrait built as a room.",
         tags=["group portrait", "the studio"]),
    dict(slug="gauguin-sunflowers", q="Gauguin Van Gogh Painting Sunflowers 1888",
         title="Van Gogh Painting Sunflowers",
         artist="Paul Gauguin (1848-1903)", date="1888",
         medium="Oil on canvas", place="Van Gogh Museum, Amsterdam",
         note="Gauguin paints his friend from behind, hunched over the canvas, and the portrait is mostly of the act of painting. Friendship recorded as shared work.",
         tags=["post-impressionism", "the studio"]),
    dict(slug="sargents-monet", q="Sargent Claude Monet Painting by the Edge of a Wood",
         title="Claude Monet Painting by the Edge of a Wood",
         artist="John Singer Sargent (1856-1925)", date="1885",
         medium="Oil on canvas", place="Tate Britain, London",
         note="Monet stands at the edge of a wood with his palette and Sargent paints him working rather than resting. Companionship recorded as shared attention.",
         tags=["impressionism", "the studio"]),

    # ---- IV. Company in the Everyday -------------------------------------
    dict(slug="card-players", q="Cezanne The Card Players",
         title="The Card Players",
         artist="Paul Cézanne (1839-1906)", date="c. 1890-95",
         medium="Oil on canvas", place="Musée d'Orsay, Paris",
         note="Two men play cards and say nothing, and the friendship is entirely in the table between them. Cézanne paints company as a shared plane.",
         tags=["post-impressionism", "silence"]),
    dict(slug="absinthe-drinker", q="Degas L'Absinthe cafe",
         title="In a Café (L'Absinthe)",
         artist="Edgar Degas (1834-1917)", date="1875-76",
         medium="Oil on canvas", place="Musée d'Orsay, Paris",
         note="A woman and a man sit side by side, each of them looking past the other. Degas paints companionship as two people occupying the same silence.",
         tags=["impressionism", "the café"]),
    dict(slug="the-balcony", file="File:Edouard Manet - The Balcony - Google Art Project.jpg",
         title="The Balcony",
         artist="Édouard Manet (1832-1883)", date="1868-69",
         medium="Oil on canvas", place="Musée d'Orsay, Paris",
         note="Three friends stand and sit on a balcony and none of them looks at any of the others, with a fourth figure in the doorway behind. Manet paints company as three separate acts of attention in one frame.",
         tags=["impressionism", "the group"]),
    dict(slug="snap-the-whip", file="File:Winslow Homer - Snap the Whip (Butler Institute of American Art).jpg",
         title="Snap the Whip",
         artist="Winslow Homer (1836-1910)", date="1872",
         medium="Oil on canvas", place="Butler Institute of American Art, Youngstown",
         note="Boys run in a line holding hands, and the friendship is the chain itself. Homer paints a group as one continuous shape across a field.",
         tags=["american", "play"]),
    dict(slug="swimming-hole", file="File:Thomas Eakins - Swimming (1895).jpg",
         title="The Swimming Hole",
         artist="Thomas Eakins (1844-1916)", date="1884-85",
         medium="Oil on canvas", place="Amon Carter Museum, Fort Worth",
         note="Six young men swim in a quarry and the friendship is the arrangement of bodies in the landscape. Eakins builds a group out of geometry, water and light.",
         tags=["american", "the group"]),

    # ---- V. Old Friends, and the Empty Chair -----------------------------
    dict(slug="two-old-men-disputing", q="Rembrandt Two Old Men Disputing",
         title="Two Old Men Disputing (Peter and Paul)",
         artist="Rembrandt van Rijn (1606-1669)", date="1628",
         medium="Oil on panel", place="National Gallery of Victoria, Melbourne",
         note="Two old men lean over a book, one of them talking and the other listening. Rembrandt paints a long friendship as an argument about a text.",
         tags=["baroque", "old age"]),
    dict(slug="two-old-men-soup", q="Goya Two Old Men Eating Soup",
         title="Two Old Men Eating Soup",
         artist="Francisco de Goya (1746-1828)", date="1820-23",
         medium="Oil on plaster transferred to canvas", place="Museo del Prado, Madrid",
         note="Two old men eat at a bare table, one of them with a skull's face at the spoon. Goya paints old company as a black joke about the body.",
         tags=["black paintings", "old age"]),
    dict(slug="gauguins-chair", q="Van Gogh Gauguin's Chair 1888",
         title="Gauguin's Chair",
         artist="Vincent van Gogh (1853-1890)", date="1888",
         medium="Oil on canvas", place="Van Gogh Museum, Amsterdam",
         note="A chair, a candle and two books, and nobody in the room. Van Gogh paints a friend by painting his empty place, which is the most abstract portrait in this gallery.",
         tags=["post-impressionism", "absence"]),
    dict(slug="gassed", q="Sargent Gassed 1919 Imperial War Museum",
         title="Gassed",
         artist="John Singer Sargent (1856-1925)", date="1919",
         medium="Oil on canvas", place="Imperial War Museum, London",
         note="A line of blinded soldiers walks with each man's hand on the shoulder of the one in front. Sargent paints comradeship as the only way anyone gets anywhere.",
         tags=["war", "the line"]),
    dict(slug="yellow-house", q="Van Gogh The Yellow House 1888",
         title="The Yellow House",
         artist="Vincent van Gogh (1853-1890)", date="1888",
         medium="Oil on canvas", place="Van Gogh Museum, Amsterdam",
         note="Van Gogh paints the house he had furnished for a friend who had not arrived yet. Friendship as a building, and as a wait.",
         tags=["post-impressionism", "the house"]),
]
