# Curated catalogue: the art of parents — mothers, fathers and children,
# weighted toward the abstract-yet-human, as in the love gallery.
#
# `file` -> exact Wikimedia Commons file title (verified to exist, PD or CC0)
# `q`    -> Commons search query; the resolver takes the first result that is
#          public domain or CC0.
#
# This is the second selection for the gallery (2026-10-06): every work is new,
# none of the plates of the first selection is reused, and every note is 5-10 words.

WORKS = [
    # ---- I. Madonna and Child ----------------------------------------------
    dict(slug="madonna-litta", file="File:Leonardo da Vinci - Madonna Litta - WGA12702.jpg",
         title="Madonna Litta",
         artist="Leonardo da Vinci (1452-1519)", date="c. 1490-91",
         medium="Tempera on canvas, transferred from panel", place="State Hermitage Museum, Saint Petersburg",
         note="A closed circuit of attention between mother and son.",
         tags=["tempera", "mother and child"]),
    dict(slug="madonna-granduca", file="File:Raphael - Madonna dell Granduca.jpg",
         title="Madonna del Granduca",
         artist="Raphael (1483-1520)", date="1505",
         medium="Oil on panel", place="Galleria Palatina, Palazzo Pitti, Florence",
         note="The mother appears out of black, the child held across.",
         tags=["high renaissance", "mother and child"]),
    dict(slug="madonna-pomegranate", file="File:Botticelli, madonna della melagrana 01.jpg",
         title="Madonna of the Pomegranate",
         artist="Sandro Botticelli (c. 1445-1510)", date="1487",
         medium="Tempera on panel", place="Galleria degli Uffizi, Florence",
         note="An emblem of fruit turned into a family gesture.",
         tags=["florentine", "mother and child"]),
    dict(slug="madonna-dove", file="File:Madonna and Child with a Dove - Piero di Cosimo - Louvre INV 817.jpg",
         title="Madonna and Child with a Dove",
         artist="Piero di Cosimo (1462-1522)", date="c. 1500",
         medium="Oil on panel", place="Musée du Louvre, Paris",
         note="The child leans out, offering a dove, off-centre.",
         tags=["florentine", "dove"]),
    dict(slug="virgin-child-st-anne", file="File:Leonardo da Vinci - Virgin and Child with St Anne C2RMF retouched.jpg",
         title="The Virgin and Child with Saint Anne",
         artist="Leonardo da Vinci (1452-1519)", date="c. 1503-19",
         medium="Oil on poplar", place="Musée du Louvre, Paris",
         note="Three generations climbing one another in a single spiral.",
         tags=["high renaissance", "three generations"]),

    # ---- II. Fathers and Sons ---------------------------------------------
    dict(slug="banjo-lesson", file="File:Henry Ossawa Tanner - The Banjo Lesson.jpg",
         title="The Banjo Lesson",
         artist="Henry Ossawa Tanner (1859-1937)", date="1893",
         medium="Oil on canvas", place="Hampton University Museum, Virginia",
         note="A lesson taught by touch, not by speech.",
         tags=["care", "teaching"]),
    dict(slug="tobit-anna", file="File:Tobit en Anna met het bokje Rijksmuseum SK-A-4717.jpeg",
         title="Tobit and Anna with the Kid",
         artist="Rembrandt van Rijn (1606-1669)", date="1626",
         medium="Oil on panel", place="Rijksmuseum, Amsterdam",
         note="Authority sits in the lap, not in the gesture.",
         tags=["interior", "household"]),
    dict(slug="old-man-grandson", file="File:Ghirlandaio, Domenico - An Old Man and His Grandson - Louvre - Google Art Project.jpg",
         title="An Old Man and His Grandson",
         artist="Domenico Ghirlandaio (1449-1494)", date="c. 1490",
         medium="Tempera on panel", place="Musée du Louvre, Paris",
         note="Two generations seen in one unmarked glance.",
         tags=["portrait", "generations"]),
    dict(slug="isaac-blessing-jacob", file="File:Govert Flinck - Isaac Blessing Jacob - WGA07930.jpg",
         title="Isaac Blessing Jacob",
         artist="Govert Flinck (1615-1660)", date="1638",
         medium="Oil on canvas", place="Rijksmuseum, Amsterdam",
         note="A blessing given to the wrong son, knowingly.",
         tags=["old testament", "blessing"]),
    dict(slug="prodigal-tavern", file="File:Rembrandt - Rembrandt and Saskia in the Scene of the Prodigal Son - Google Art Project.jpg",
         title="The Prodigal Son in the Tavern",
         artist="Rembrandt van Rijn (1606-1669)", date="c. 1635",
         medium="Oil on canvas", place="Gemäldegalerie Alte Meister, Dresden",
         note="The father is absent, which is the whole point.",
         tags=["parable", "self-portrait"]),

    # ---- III. The Artist's Own Parents ------------------------------------
    dict(slug="cezanne-mother", file="File:Portrait of the Artist’s Mother by Paul Cézanne, 1866-1867, oil on canvas, Saint Louis Art Museum.jpg",
         title="Portrait of the Artist's Mother",
         artist="Paul Cézanne (1839-1906)", date="1866-67",
         medium="Oil on canvas", place="Saint Louis Art Museum",
         note="A son's first portrait, and his most unsentimental.",
         tags=["portrait", "unsentimental"]),
    dict(slug="orlai-mother", file="File:Orlai Portrait of the Artist's Mother 1853.jpg",
         title="Portrait of the Artist's Mother",
         artist="Soma Orlai Petrich (1822-1880)", date="1853",
         medium="Oil on canvas", place="Private collection",
         note="Ordinary dress, ordinary room, and no ideal anywhere.",
         tags=["portrait", "domestic"]),
    dict(slug="tanner-mother", file="File:Henry Ossawa Tanner, American (active France) - Portrait of the Artist's Mother - Google Art Project.jpg",
         title="Portrait of the Artist's Mother",
         artist="Henry Ossawa Tanner (1859-1937)", date="1897",
         medium="Oil on canvas", place="Philadelphia Museum of Art",
         note="The tenderness is in how little the son intrudes.",
         tags=["portrait", "low key"]),
    dict(slug="ensor-father", file="File:James Ensor - Portrait of the Artist's Father.jpg",
         title="Portrait of the Artist's Father",
         artist="James Ensor (1860-1949)", date="1882",
         medium="Oil on canvas", place="",
         note="A formal portrait threatening to become a mask.",
         tags=["portrait", "mask"]),
    dict(slug="mancini-father", file="File:Antonio Mancini - A Portrait of the Artist's Father.jpg",
         title="Portrait of the Artist's Father",
         artist="Antonio Mancini (1852-1930)", date="undated",
         medium="Oil on canvas", place="Private collection",
         note="A likeness that refuses to finish itself.",
         tags=["portrait", "unfinished"]),

    # ---- IV. The Everyday Work of Care ------------------------------------
    dict(slug="cassatt-oval-mirror", file="File:Mother and Child (The Oval Mirror) MET DT2025.jpg",
         title="Mother and Child (The Oval Mirror)",
         artist="Mary Cassatt (1844-1926)", date="c. 1899",
         medium="Oil on canvas", place="The Metropolitan Museum of Art, New York",
         note="The embrace described by the shape of the frame.",
         tags=["impressionism", "mirror"]),
    dict(slug="cassatt-combing", file="File:Brooklyn Museum - Mother Combing Her Child's Hair - Mary Cassatt.jpg",
         title="Mother Combing Her Child's Hair",
         artist="Mary Cassatt (1844-1926)", date="c. 1901",
         medium="Pastel and gouache on tan paper", place="Brooklyn Museum, New York",
         note="The chore of hair described as holding still.",
         tags=["pastel", "care"]),
    dict(slug="cassatt-nurse-reading", file="File:Nurse Reading to a Little Girl MET DT7250.jpg",
         title="Nurse Reading to a Little Girl",
         artist="Mary Cassatt (1844-1926)", date="1895",
         medium="Pastel on wove paper, mounted on canvas", place="The Metropolitan Museum of Art, New York",
         note="Two people agreeing to spend one quiet hour.",
         tags=["pastel", "reading"]),
    dict(slug="morisot-garden", file="File:Berthe Morisot - A Woman and Child in a Garden - NG 2269 - National Galleries of Scotland.jpg",
         title="A Woman and Child in a Garden",
         artist="Berthe Morisot (1841-1895)", date="c. 1883-84",
         medium="Oil on canvas", place="National Galleries of Scotland, Edinburgh",
         note="The garden where the pair is allowed to be ordinary.",
         tags=["impressionism", "garden"]),
    dict(slug="morisot-meadow", file="File:Berthe Morisot - Woman and Child Seated in a Meadow (1871).jpg",
         title="Woman and Child Seated in a Meadow",
         artist="Berthe Morisot (1841-1895)", date="1871",
         medium="Watercolour on paper", place="",
         note="Two figures on grass, and nothing else at all.",
         tags=["watercolour", "leisure"]),

    # ---- V. Grief, and the Night -----------------------------------------
    dict(slug="bouguereau-pieta", file="File:William-Adolphe Bouguereau (1825-1905) - Pieta (1876).jpg",
         title="Pietà",
         artist="William-Adolphe Bouguereau (1825-1905)", date="1876",
         medium="Oil on canvas", place="",
         note="Academic finish makes the loss harder to look at.",
         tags=["academic", "mourning"]),
    dict(slug="michelangelo-pieta", file="File:Michelangelo's Pietà Saint Peter's Basilica Vatican City.jpg",
         title="Pietà",
         artist="Michelangelo (1475-1564)", date="1498-99",
         medium="Marble", place="St Peter's Basilica, Vatican City",
         note="The moment a parent outlives the child.",
         tags=["sculpture", "marble"]),
    dict(slug="klimt-death-life", file="File:Gustav Klimt - Death and Life - Google Art Project.jpg",
         title="Death and Life",
         artist="Gustav Klimt (1862-1918)", date="1910/15",
         medium="Oil on canvas", place="Leopold Museum, Vienna",
         note="The family is what death has to pry apart.",
         tags=["symbolism", "sleep"]),
    dict(slug="munch-deathbed", file="File:'At the Deathbed' by Edvard Munch, 1895, Bergen Kunstmuseum.JPG",
         title="At the Deathbed",
         artist="Edvard Munch (1863-1944)", date="1895",
         medium="Oil and tempera on canvas", place="Bergen Kunstmuseum",
         note="A household turning into a row of separate people.",
         tags=["expressionism", "grief"]),
    dict(slug="munch-sickroom", file="File:Edvard Munch - Death in the Sickroom - MM.M.00214 - Munch Museum.jpg",
         title="Death in the Sickroom",
         artist="Edvard Munch (1863-1944)", date="1893",
         medium="Pastel", place="Munch Museum, Oslo",
         note="The room is the illness; sitting still is comfort.",
         tags=["expressionism", "illness"]),
]
