#!/usr/bin/env python3
"""Write works.py from the selected hope works, with the licence label resolved.

The harvest stored the licence section of each file page as raw wikitext; this pulls the
licence template out of it so every plate can carry a plain label in the catalogue.
"""
import json
import os
import re
import sys

BASE = os.path.dirname(os.path.abspath(__file__))
SELECTED = os.environ.get("HOPE_SELECTED", "/tmp/hope3-selected.json")
CANDS = "/tmp/hope-candidates.json"

LIC = re.compile(r"\{\{\s*(PD-[A-Za-z0-9\-_.]+|CC-zero|cc-zero|CC0[^}|]*|"
                 r"PD-self|PD-Art|PD-scan|PD-US[^}|]*)", re.I)
PREFER = re.compile(r"^(PD-Art|PD-old-70|PD-old|PD-US-expired|PD-scan|PD-1923|"
                    r"PD-self|PD-1996|CC-zero|PD-US)", re.I)


def label(text):
    found = [m.group(1).strip() for m in LIC.finditer(text or "")]
    if not found:
        return "public domain"
    for f in found:
        if PREFER.match(f):
            return f
    return found[0]


def main():
    selected = json.load(open(SELECTED))
    cands = {c["file_title"]: c for c in json.load(open(CANDS))}
    # a work whose image never arrived is dropped rather than left as a broken plate
    works = []
    for w in selected:
        c = cands.get(w["file_title"], {})
        works.append(dict(
            slug=w["slug"], file=w["file_title"],
            license=label(c.get("license_section")),
            artist=w["artist"], title=w["title"], date=w["date"],
            medium=w["medium"], institution=w["institution"],
            dimensions=w["dimensions"], source=w["source"],
            section=w["section"], section_title=w["section_title"],
            blurb=w["blurb"], categories=w["categories"]))
    out = os.path.join(BASE, "works.py")
    with open(out, "w") as f:
        f.write('"""The works of the hope/merging gallery, generated by gen_works.py."""\n\n')
        f.write("WORKS = ")
        json.dump(works, f, ensure_ascii=False, indent=1)
        f.write("\n")
    print(f"{len(works)} works written to {out}")
    import collections
    print(collections.Counter(w["license"] for w in works).most_common(12))
    print(collections.Counter(w["section"] for w in works))


if __name__ == "__main__":
    main()
