# Curated catalogue: classical art on love, weighted toward the abstract-yet-human.
#
# `file`  -> exact Wikimedia Commons file title (verified to exist)
# `q`     -> Commons search query, used when no exact title is pinned
# Every entry is public domain or CC0; no CC BY-SA photographs are included.

WORKS = [
    # ---- I. Allegory and Emblem -------------------------------------------
    dict(slug="sacred-profane-love", q="Titian Sacred and Profane Love Borghese",
         title="Sacred and Profane Love",
         artist="Titian (c. 1488/90-1576)", date="c. 1514",
         medium="Oil on canvas", place="Galleria Borghese, Rome",
         note="Two women sit at a well — one dressed, one bare — while a child stirs the water between them. The allegory is left unresolved on purpose: the same body shown twice, as thought and as feeling.",
         tags=["allegory", "venetian colour"]),
    dict(slug="venus-and-mars", file="File:Venus and Mars National Gallery.jpg",
         title="Venus and Mars",
         artist="Sandro Botticelli (c. 1445-1510)", date="c. 1485",
         medium="Tempera and oil on poplar", place="National Gallery, London",
         note="Mars sleeps while wasps hum about his head and Venus watches, propped and awake. Love here is not an event but a condition — vigilance kept beside oblivion.",
         tags=["allegory", "line"]),
    dict(slug="allegory-venus-cupid", file="File:Angelo Bronzino - Venus, Cupid, Folly and Time - National Gallery, London.jpg",
         title="An Allegory with Venus and Cupid",
         artist="Agnolo Bronzino (1503-1572)", date="c. 1545",
         medium="Oil on panel", place="National Gallery, London",
         note="Cold, enamelled, almost mineral flesh, with Time and Folly drawing back the curtain. Desire is argued as geometry rather than felt on the skin.",
         tags=["mannerism", "allegory"]),
    dict(slug="primavera", file="File:Sandro Botticelli - La Primavera - Google Art Project.jpg",
         title="Primavera",
         artist="Sandro Botticelli (c. 1445-1510)", date="c. 1480",
         medium="Tempera on panel", place="Galleria degli Uffizi, Florence",
         note="Nine figures stand in an orange grove and almost none of them touch. Spring, love and fertility are arranged as a diagram — an argument made out of bodies.",
         tags=["allegory", "neoplatonism"]),
    dict(slug="venus-of-urbino", file="File:Tiziano - Venere di Urbino - Google Art Project.jpg",
         title="Venus of Urbino",
         artist="Titian (c. 1488/90-1576)", date="1538",
         medium="Oil on canvas", place="Galleria degli Uffizi, Florence",
         note="A goddess installed in an ordinary Venetian bedroom, looking straight out of the picture. The body has become a painted surface first and a person second, which is exactly what makes the gaze so unsettled.",
         tags=["venetian colour", "gaze"]),

    # ---- II. The Symbolist Dream ------------------------------------------
    dict(slug="the-cyclops", file="File:Odilon Redon - The Cyclops, c. 1914.jpg",
         title="The Cyclops",
         artist="Odilon Redon (1840-1916)", date="c. 1914",
         medium="Oil on canvas", place="Kröller-Müller Museum, Otterlo",
         note="One enormous eye rises over the hills to look at a sleeping woman. Desire is reduced to a single organ, watching — the most abstract thing a body can do.",
         tags=["symbolism", "dream"]),
    dict(slug="the-caress", file="File:Fernand Khnopff - Caresses - Google Art Project.jpg",
         title="The Caress",
         artist="Fernand Khnopff (1858-1921)", date="1896",
         medium="Oil on canvas", place="Musées royaux des Beaux-Arts, Brussels",
         note="A woman with a cheetah's head rests her cheek against a young man's. Tenderness and predation share one silhouette, and the human face is withheld altogether.",
         tags=["symbolism", "sphinx"]),
    dict(slug="jupiter-and-semele", file="File:Jupiter and Semele by Gustave Moreau.jpg",
         title="Jupiter and Semele",
         artist="Gustave Moreau (1826-1898)", date="1894-95",
         medium="Oil on canvas", place="Musée Gustave Moreau, Paris",
         note="The god arrives as a wall of gold and flowers, and the mortal dissolves into the ornament that destroys her. Love rendered as architecture.",
         tags=["symbolism", "ornament"]),
    dict(slug="kiss-of-the-sphinx", file="File:Franz von Stuck - The Kiss of the Sphinx - Google Art Project.jpg",
         title="The Kiss of the Sphinx",
         artist="Franz von Stuck (1863-1928)", date="1895",
         medium="Oil on canvas", place="Museum Villa Stuck, Munich",
         note="The embrace is also an ambush. Two bodies lock into a single dark mass and it is impossible to tell which one is being consumed.",
         tags=["symbolism", "sphinx"]),
    dict(slug="lovers-whirlwind", file="File:Blake Dante Hell V.jpg",
         title="The Lovers' Whirlwind, Paolo and Francesca",
         artist="William Blake (1757-1827)", date="c. 1824-27",
         medium="Graphite, ink and watercolour on paper", place="Birmingham Museum and Art Gallery",
         note="The adulterous lovers are spun through hell as one vortex of limbs. Blake draws passion as weather — bodies turned into motion rather than flesh.",
         tags=["line", "visionary"]),
    dict(slug="beata-beatrix", file="File:Dante Gabriel Rossetti - Beata Beatrix, 1864-1870.jpg",
         title="Beata Beatrix",
         artist="Dante Gabriel Rossetti (1828-1882)", date="1864-70",
         medium="Oil on canvas", place="Tate Britain, London",
         note="Beatrice sits with closed eyes while a red bird drops a white poppy into her hand. Love and death occupy the same still, luminous face.",
         tags=["pre-raphaelite", "memorial"]),

    # ---- III. Line and Gesture --------------------------------------------
    dict(slug="mars-venus-cupid", q="Mars Venus and Cupid Marcantonio Raimondi 1508 engraving",
         title="Mars, Venus, and Cupid",
         artist="Marcantonio Raimondi (c. 1480-1534), after Raphael", date="1508",
         medium="Engraving", place="The Metropolitan Museum of Art, New York",
         note="War disarmed by desire: the god of battle stripped of his armour and reduced to a seated outline, watched by a small winged boy.",
         tags=["line", "engraving"]),
    dict(slug="venus-disarming-cupid", file="File:Parmigianino - Venus Disarming Cupid - Google Art Project.jpg",
         title="Venus Disarming Cupid",
         artist="Parmigianino (1503-1540)", date="c. 1524-30",
         medium="Drawing", place="",
         note="A few hundred strokes and the whole of a love affair exists: Venus takes Cupid's arrow from him while he twists away. Mannerist drawing at its most abstract, the figure stated as curve and shadow and very little else.",
         tags=["line", "mannerism"]),
    dict(slug="saskia", file="File:Self-Portrait with Saskia MET DP814514.jpg",
         title="Self-Portrait with Saskia",
         artist="Rembrandt van Rijn (1606-1669)", date="1636",
         medium="Etching", place="The Metropolitan Museum of Art, New York",
         note="Rembrandt draws himself and his wife at a tavern table in a few dozen etched lines. Tenderness recorded as a shared glance and a raised glass.",
         tags=["etching", "intimacy"]),
    dict(slug="paolo-francesca", file="File:Gustave Doré - Paolo and Francesca da Rimini.jpg",
         title="Paolo and Francesca",
         artist="Gustave Doré (1832-1883)", date="1861",
         medium="Wood engraving for Dante's Inferno, Canto V",
         note="The two lovers drift in the circle of the lustful, still entwined, weightless and unrepentant. Doré engraves damnation as a texture of light and air.",
         tags=["line", "engraving"]),

    # ---- IV. The Body as Form ---------------------------------------------
    dict(slug="the-kiss-rodin", file="File:Le Baiser (detail, Musee Rodin, Paris)-2014-05.jpg",
         title="The Kiss (detail)",
         artist="Auguste Rodin (1840-1917)", date="1882, carved 1901-04",
         medium="Marble", place="Musée Rodin, Paris",
         note="Two bodies cut from a single block, so the embrace is also one mass. The most literal of subjects made the most sculptural.",
         tags=["sculpture", "marble"]),
    dict(slug="eternal-springtime", q="Eternal Springtime Auguste Rodin Huntington bronze",
         title="Eternal Springtime",
         artist="Auguste Rodin (1840-1917)", date="1884, cast c. 1886",
         medium="Bronze", place="Huntington Museum of Art",
         note="The figures lean out of the block they were never fully freed from. Movement and tenderness held in the same unfinished gesture.",
         tags=["sculpture", "bronze"]),
    dict(slug="psyche-revived", file="File:Psyché ranimée par le baiser de l'Amour, Louvre.jpg",
         title="Psyche Revived by Cupid's Kiss",
         artist="Antonio Canova (1757-1822)", date="1787-93",
         medium="Marble", place="Musée du Louvre, Paris",
         note="Cupid's hands and wings are the only support; Psyche's body is weightless, held up by tenderness. Neoclassical marble at its most tender.",
         tags=["sculpture", "marble"]),
    dict(slug="the-waltz", file='File:Camille Claudel, "La Valse", 1889-1905, bronze fonte (1).jpg',
         title="The Waltz",
         artist="Camille Claudel (1864-1943)", date="1889-1905",
         medium="Bronze", place="Musée Camille Claudel, Nogent-sur-Seine",
         note="Two figures turn until the dress becomes the movement itself. Claudel sculpts the turn rather than the dancers.",
         tags=["sculpture", "movement"]),

    # ---- V. The Threshold of Modernity ------------------------------------
    dict(slug="kiss-klimt", file="File:Klimt - The Kiss.jpg",
         title="The Kiss",
         artist="Gustav Klimt (1862-1918)", date="1907-08",
         medium="Oil and gold leaf on canvas", place="Österreichische Galerie Belvedere, Vienna",
         note="Two faces are almost lost inside the gold. Klimt buries the human in ornament, and the tenderness survives the pattern.",
         tags=["gold", "ornament"]),
    dict(slug="liebe-klimt", file="File:Klimt - Liebe - 1895.jpeg",
         title="Love",
         artist="Gustav Klimt (1862-1918)", date="1895",
         medium="Oil on canvas", place="Kunsthistorisches Museum, Vienna",
         note="A stack of pale, doubled faces, haloed and interchangeable. Love painted as a condition shared rather than a scene observed.",
         tags=["symbolism", "ornament"]),
    dict(slug="madonna-munch", file="File:Edvard Munch - Madonna - Google Art Project.jpg",
         title="Madonna",
         artist="Edvard Munch (1863-1944)", date="1894-95",
         medium="Oil on canvas", place="Munch Museum, Oslo",
         note="Love and death share one body, and the halo is also the red halo of pain. The face is bowed into anonymity.",
         tags=["expressionism", "symbolism"]),
    dict(slug="kiss-munch", file="File:Edvard Munch - The Kiss - Google Art Project.jpg",
         title="The Kiss",
         artist="Edvard Munch (1863-1944)", date="1897",
         medium="Oil on canvas", place="Munch Museum, Oslo",
         note="Two faces merge into a single featureless mass. Munch paints the moment identity stops at the edge of the other person.",
         tags=["expressionism", "frieze"]),
    dict(slug="umarmung-schiele", file="File:Egon Schiele - Umarmung (1917).jpg",
         title="The Embrace",
         artist="Egon Schiele (1890-1918)", date="1917",
         medium="Oil on canvas", place="Österreichische Galerie Belvedere, Vienna",
         note="Bodies drawn as angles and stains, awkward and specific. Schiele keeps every joint human while the colour runs free of the contour.",
         tags=["expressionism", "line"]),
    dict(slug="dance-of-life", file="File:Edvard Munch - The dance of life (1899-1900).jpg",
         title="The Dance of Life",
         artist="Edvard Munch (1863-1944)", date="1899-1900",
         medium="Oil on canvas", place="National Museum, Oslo",
         note="Three women stand on a summer shore while couples dance behind them: the white of innocence, the red of love, the black of grief. A whole life arranged as one dance.",
         tags=["allegory", "frieze"]),

    # ---- I. Allegory and Emblem (continued) ---------------------------------
    dict(slug="birth-of-venus", q="Botticelli The Birth of Venus Uffizi",
         title="The Birth of Venus",
         artist="Sandro Botticelli (c. 1445-1510)", date="c. 1485",
         medium="Tempera on canvas", place="Galleria degli Uffizi, Florence",
         note="Venus arrives on a shell blown in by the winds, and love is staged as a birth rather than a meeting. Botticelli paints desire as weather, flowers and hair, with the body barely touching anything.",
         tags=["allegory", "mythology"]),
    dict(slug="venus-with-mirror", q="Titian Venus with a Mirror National Gallery of Art",
         title="Venus with a Mirror",
         artist="Titian (c. 1488/90-1576)", date="c. 1555",
         medium="Oil on canvas", place="National Gallery of Art, Washington",
         note="The goddess looks at herself while a cupid holds the mirror, and the only love in the picture is self-regard. The body has become a surface being admired, and the admirer is her.",
         tags=["venetian colour", "the mirror"]),
    dict(slug="garden-of-love", q="Rubens The Garden of Love Prado",
         title="The Garden of Love",
         artist="Peter Paul Rubens (1577-1640)", date="c. 1633",
         medium="Oil on canvas", place="Museo del Prado, Madrid",
         note="Rubens gathers his wife, his friends and a fountain of Venus into one garden, and love is described as a social occasion rather than a private one.",
         tags=["baroque", "allegory"]),
    dict(slug="embarkation-cythera", q="Watteau Embarkation for Cythera Louvre",
         title="The Embarkation for Cythera",
         artist="Antoine Watteau (1684-1721)", date="1717",
         medium="Oil on canvas", place="Musée du Louvre, Paris",
         note="Lovers set out for the island of Venus, or are returning from it, and nobody can tell which. Love painted as a departure that has already become a memory.",
         tags=["rococo", "allegory"]),
    dict(slug="mars-venus-veronese", q="Veronese Mars and Venus United by Love Metropolitan Museum",
         title="Mars and Venus United by Love",
         artist="Paolo Veronese (1528-1588)", date="c. 1570",
         medium="Oil on canvas", place="The Metropolitan Museum of Art, New York",
         note="Veronese ties the god of war to the goddess with a knot of ribbon while a cupid pulls it tight, and love is literally a knot in the composition.",
         tags=["venetian colour", "allegory"]),

    # ---- II. The Symbolist Dream (continued) --------------------------------
    dict(slug="ophelia-redon", q="Odilon Redon Ophelia among the Flowers",
         title="Ophelia among the Flowers",
         artist="Odilon Redon (1840-1916)", date="c. 1905-08",
         medium="Pastel and charcoal", place="National Gallery, London",
         note="Ophelia floats in a river of flowers with her mouth open, and Redon paints love's grief as a colour rather than an event. The face is almost lost in the blue.",
         tags=["symbolism", "dream"]),
    dict(slug="the-apparition", q="Gustave Moreau The Apparition Salome",
         title="The Apparition",
         artist="Gustave Moreau (1826-1898)", date="1876",
         medium="Oil on canvas", place="Musée Gustave Moreau, Paris",
         note="Salome stands before the head of the man she desired and the vision glows in the air between them. Moreau paints obsession as an apparition, and the body as ornament.",
         tags=["symbolism", "ornament"]),
    dict(slug="love-among-ruins", q="Burne-Jones Love Among the Ruins",
         title="Love Among the Ruins",
         artist="Edward Burne-Jones (1833-1898)", date="1870-73",
         medium="Oil on canvas", place="Wightwick Manor, Wolverhampton",
         note="Two lovers sit among brambles while a figure behind them plays a lute, and love is described as a place rather than a feeling.",
         tags=["pre-raphaelite", "allegory"]),
    dict(slug="the-beloved", q="Rossetti The Beloved 1866",
         title="The Beloved",
         artist="Dante Gabriel Rossetti (1828-1882)", date="1865-66",
         medium="Oil on canvas", place="Tate Britain, London",
         note="Rossetti crowds the bride with her companions until her face is only one among many, and love is painted as an enclosed garden.",
         tags=["pre-raphaelite", "the garden"]),

    # ---- III. Line and Gesture (continued) ---------------------------------
    dict(slug="venus-cupid-niche", q="Venus and Cupid standing in a niche Raimondi Metropolitan",
         title="Venus and Cupid in a Niche",
         artist="Marcantonio Raimondi (c. 1480-1534)", date="c. 1500-27",
         medium="Engraving", place="The Metropolitan Museum of Art, New York",
         note="A goddess and a small winged boy stand inside a shell-shaped niche, and love is described by hatching and architecture alone.",
         tags=["line", "engraving"]),
    dict(slug="ill-assorted-couple", q="Durer The Ill-Assorted Couple engraving",
         title="The Ill-Assorted Couple",
         artist="Albrecht Dürer (1471-1528)", date="c. 1495",
         medium="Engraving", place="",
         note="An old man and a young woman walk together and exchange a glance that is entirely about money. Dürer engraves a love affair as a transaction, which is one of the most honest images of one.",
         tags=["line", "engraving"]),
    dict(slug="jupiter-antiope", q="Rembrandt Jupiter and Antiope etching 1659",
         title="Jupiter and Antiope",
         artist="Rembrandt van Rijn (1606-1669)", date="1659",
         medium="Etching", place="Rijksmuseum, Amsterdam",
         note="Jupiter approaches the sleeping Antiope in the dark, and the whole of desire is in one raised hand and one shadow. Rembrandt etches seduction as an arrangement of light.",
         tags=["etching", "desire"]),
    dict(slug="liebespaar-klimt", q="Gustav Klimt Liebespaar drawing",
         title="Lovers",
         artist="Gustav Klimt (1862-1918)", date="c. 1913",
         medium="Pencil and white chalk on paper", place="",
         note="Two lovers are drawn as a single line of pencil and chalk with their heads pressed together. The drawing is almost entirely contour, and unmistakably two people.",
         tags=["line", "drawing"]),
    dict(slug="liebespaar-schiele", q="Egon Schiele Liebespaar lovers drawing",
         title="Lovers",
         artist="Egon Schiele (1890-1918)", date="c. 1917",
         medium="Pencil and gouache on paper", place="",
         note="Schiele draws two bodies as angles and stains, awkward and specific, and the tenderness survives every distortion.",
         tags=["line", "expressionism"]),
    dict(slug="lovers-rodin-drawing", q="Rodin drawing lovers watercolour",
         title="Two Lovers",
         artist="Auguste Rodin (1840-1917)", date="c. 1900",
         medium="Pencil and watercolour on paper", place="Musée Rodin, Paris",
         note="Rodin draws a pair of lovers in a few sweeps of pencil and watercolour, and the bodies are almost dissolved in the colour. The most abstract of all his images of love.",
         tags=["line", "watercolour"]),

    # ---- IV. The Body as Form (continued) ----------------------------------
    dict(slug="the-eternal-idol", q="Rodin The Eternal Idol bronze",
         title="The Eternal Idol",
         artist="Auguste Rodin (1840-1917)", date="1889, cast later",
         medium="Bronze", place="Musée Rodin, Paris",
         note="A woman kneels and a man bends his head to her shoulder, and the two bodies lock into one vertical mass. Rodin called it the eternal idol, which is love as worship.",
         tags=["sculpture", "bronze"]),
    dict(slug="fugit-amor", q="Rodin Fugit Amor sculpture marble",
         title="Fugit Amor",
         artist="Auguste Rodin (1840-1917)", date="c. 1885-87",
         medium="Marble and bronze", place="Musée Rodin, Paris",
         note="Two figures are pulled apart in mid-air and their hands cannot reach each other, and love is a departure that has already happened. The most abstract of Rodin's love groups.",
         tags=["sculpture", "marble"]),
    dict(slug="three-graces-canova", q="Canova The Three Graces Hermitage",
         title="The Three Graces",
         artist="Antonio Canova (1757-1822)", date="1814-17",
         medium="Marble", place="Hermitage Museum, Saint Petersburg",
         note="Three women stand linked by their arms and shoulders, and the group is one continuous soft curve. Grace described as a single line rather than three bodies.",
         tags=["sculpture", "marble"]),
    dict(slug="amor-psyche-canova", q="Canova Amor and Psyche Hermitage",
         title="Amor and Psyche",
         artist="Antonio Canova (1757-1822)", date="1793",
         medium="Marble", place="Hermitage Museum, Saint Petersburg",
         note="Cupid stands with his arm around Psyche and a butterfly resting on his hand, and love is described as a balance between two standing bodies.",
         tags=["sculpture", "marble"]),
    dict(slug="eros-stringing-bow", q="Eros stringing the bow Roman marble",
         title="Eros Stringing the Bow",
         artist="Roman, after Lysippos", date="1st-2nd century AD",
         medium="Marble", place="",
         note="The god of love bends his bow and looks up, and the whole of desire is in the tension of one arm. Ancient sculpture at its most abstract and most human.",
         tags=["marble", "desire"]),
    dict(slug="sakuntala", q="Camille Claudel Sakuntala bronze",
         title="Sakuntala",
         artist="Camille Claudel (1864-1943)", date="1886-1905",
         medium="Marble and bronze", place="Musée Camille Claudel, Nogent-sur-Seine",
         note="A woman leans back against a man who holds her upright, and the two bodies make one exhausted diagonal. Claudel carves love as a form of collapse.",
         tags=["sculpture", "bronze"]),

    # ---- V. The Threshold of Modernity (continued) --------------------------
    dict(slug="danae-klimt", q="Gustav Klimt Danae 1907",
         title="Danaë",
         artist="Gustav Klimt (1862-1918)", date="1907-08",
         medium="Oil on canvas", place="Galerie Belvedere, Vienna",
         note="Danaë curls into a spiral inside a veil of gold with her face almost hidden, and love is painted as a shower of gold rather than as a body.",
         tags=["gold", "ornament"]),
    dict(slug="water-serpents", q="Gustav Klimt Water Serpents",
         title="Water Serpents",
         artist="Gustav Klimt (1862-1918)", date="1904-07",
         medium="Oil on canvas", place="Galerie Belvedere, Vienna",
         note="Two women embrace in water until their hair and their bodies dissolve into pattern. Klimt paints desire as ornament, and ornament as desire.",
         tags=["gold", "ornament"]),
    dict(slug="vampire-munch", q="Munch Vampire 1893",
         title="Vampire (Love and Pain)",
         artist="Edvard Munch (1863-1944)", date="1893",
         medium="Oil on canvas", place="Munch Museum, Oslo",
         note="A woman bends over a man's neck and his face is buried in her hair, and the red hair covers the whole composition. Munch paints love as a wound.",
         tags=["expressionism", "frieze"]),
    dict(slug="ashes-munch", q="Munch Ashes 1894",
         title="Ashes",
         artist="Edvard Munch (1863-1944)", date="1894",
         medium="Oil on canvas", place="National Museum, Oslo",
         note="A woman stands upright in the forest while a man sits with his head in his hands, and the fire between them is already out. Love painted as aftermath.",
         tags=["expressionism", "frieze"]),
]
